import type { Metadata } from "next";
import "../styles/normalize.scss";
import "../styles/globals.scss";

export const metadata: Metadata = {
  title: "PROGRES.COM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body>
        <header>
          <h1>Header</h1>
        </header>
        <main>{children}</main>
        <footer>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
